"""Country ID → name lookup for the Global Gateway analytics export format.

Source: Trulioo.GlobalGateway.Core.Enums.CountryEnum, package version 6.0.7
(252 entries, generated 2026-07-20).

Used by analytics_format.py to resolve the countryId integer column in
analytics export CSVs into human-readable country names before classification.
"""

from __future__ import annotations

import math

_ID_TO_NAME: dict[int, str] = {
    -1: "Global",
    0: "Unknown",
    1: "Australia",
    2: "United States",
    3: "Andorra",
    4: "United Arab Emirates",
    5: "Afghanistan",
    6: "Antigua and Barbuda",
    7: "Anguilla",
    8: "Albania",
    9: "Armenia",
    10: "Netherlands Antilles",
    11: "Angola",
    12: "Antarctica",
    13: "Argentina",
    14: "American Samoa",
    15: "Austria",
    16: "Aruba",
    17: "Azerbaijan",
    18: "Bosnia and Herzegovina",
    19: "Barbados",
    20: "Bangladesh",
    21: "Belgium",
    22: "Burkina Faso",
    23: "Bulgaria",
    24: "Bahrain",
    25: "Burundi",
    26: "Benin",
    27: "Bermuda",
    28: "Brunei Darussalam",
    29: "Bolivia",
    30: "Brazil",
    31: "Bahamas",
    32: "Bhutan",
    33: "Bouvet Island",
    34: "Botswana",
    35: "Belarus",
    36: "Belize",
    37: "Canada",
    38: "Cocos (Keeling) Islands",
    39: "Congo, the Democratic Republic of the",
    40: "Central African Republic",
    41: "Congo",
    42: "Switzerland",
    43: "Cote D'Ivoire",
    44: "Cook Islands",
    45: "Chile",
    46: "Cameroon",
    47: "China",
    48: "Colombia",
    49: "Costa Rica",
    50: "Serbia and Montenegro",
    51: "Cuba",
    52: "Cape Verde",
    53: "Christmas Island",
    54: "Cyprus",
    55: "Czech Republic",
    56: "Germany",
    57: "Djibouti",
    58: "Denmark",
    59: "Dominica",
    60: "Dominican Republic",
    61: "Algeria",
    62: "Ecuador",
    63: "Estonia",
    64: "Egypt",
    65: "Western Sahara",
    66: "Eritrea",
    67: "Spain",
    68: "Ethiopia",
    69: "Finland",
    70: "Fiji",
    71: "Falkland Islands (Malvinas)",
    72: "Micronesia, Federated States of",
    73: "Faroe Islands",
    74: "France",
    75: "Gabon",
    76: "Grenada",
    77: "Georgia",
    78: "French Guiana",
    79: "Ghana",
    80: "Gibraltar",
    81: "Greenland",
    82: "Gambia",
    83: "Guinea",
    84: "Guadeloupe",
    85: "Equatorial Guinea",
    86: "Greece",
    87: "South Georgia and the South Sandwich Islands",
    88: "Guatemala",
    89: "Guam",
    90: "Guinea-Bissau",
    91: "Guyana",
    92: "Hong Kong",
    93: "Heard Island and McDonald Islands",
    94: "Honduras",
    95: "Croatia",
    96: "Haiti",
    97: "Hungary",
    98: "Indonesia",
    99: "Ireland",
    100: "Israel",
    101: "India",
    102: "British Indian Ocean Territory",
    103: "Iraq",
    104: "Iran, Islamic Republic of",
    105: "Iceland",
    106: "Italy",
    107: "Jersey",
    108: "Jamaica",
    109: "Jordan",
    110: "Japan",
    111: "Kenya",
    112: "Kyrgyzstan",
    113: "Cambodia",
    114: "Kiribati",
    115: "Comoros",
    116: "Saint Kitts and Nevis",
    117: "Korea, Democratic People's Republic of",
    118: "Korea, Republic of",
    119: "Kuwait",
    120: "Cayman Islands",
    121: "Kazakhstan",
    122: "Lao People's Democratic Republic",
    123: "Lebanon",
    124: "Saint Lucia",
    125: "Liechtenstein",
    126: "Sri Lanka",
    127: "Liberia",
    128: "Lesotho",
    129: "Lithuania",
    130: "Luxembourg",
    131: "Latvia",
    132: "Libyan Arab Jamahiriya",
    133: "Morocco",
    134: "Saint Martin",
    135: "Monaco",
    136: "Moldova, Republic of",
    137: "Madagascar",
    138: "Marshall Islands",
    139: "Macedonia, the Former Yugoslav Republic of",
    140: "Mali",
    141: "Myanmar",
    142: "Mongolia",
    143: "Macao",
    144: "Northern Mariana Islands",
    145: "Martinique",
    146: "Mauritania",
    147: "Montserrat",
    148: "Malta",
    149: "Mauritius",
    150: "Maldives",
    151: "Malawi",
    152: "Mexico",
    153: "Malaysia",
    154: "Mozambique",
    155: "Namibia",
    156: "New Caledonia",
    157: "Niger",
    158: "Norfolk Island",
    159: "Nigeria",
    160: "Nicaragua",
    161: "Netherlands",
    162: "Norway",
    163: "Nepal",
    164: "Nauru",
    165: "Niue",
    166: "New Zealand",
    167: "Oman",
    168: "Panama",
    169: "Peru",
    170: "French Polynesia",
    171: "Papua New Guinea",
    172: "Philippines",
    173: "Pakistan",
    174: "Poland",
    175: "Saint Pierre and Miquelon",
    176: "Pitcairn",
    177: "Puerto Rico",
    178: "Palestinian Territory, Occupied",
    179: "Portugal",
    180: "Palau",
    181: "Paraguay",
    182: "Qatar",
    183: "Reunion",
    184: "Romania",
    185: "Russian Federation",
    186: "Rwanda",
    187: "Saudi Arabia",
    188: "Solomon Islands",
    189: "Seychelles",
    190: "Sudan",
    191: "Sweden",
    192: "Singapore",
    193: "Saint Helena",
    194: "Slovenia",
    195: "Svalbard and Jan Mayen",
    196: "Slovakia",
    197: "Sierra Leone",
    198: "San Marino",
    199: "Senegal",
    200: "Somalia",
    201: "Suriname",
    202: "Sao Tome and Principe",
    203: "El Salvador",
    204: "Syrian Arab Republic",
    205: "Eswatini",
    206: "Turks and Caicos Islands",
    207: "Chad",
    208: "French Southern Territories",
    209: "Togo",
    210: "Thailand",
    211: "Tajikistan",
    212: "Tokelau",
    213: "Timor-Leste",
    214: "Turkmenistan",
    215: "Tunisia",
    216: "Tonga",
    217: "Türkiye",
    218: "Trinidad and Tobago",
    219: "Tuvalu",
    220: "Taiwan, Province of China",
    221: "Tanzania, United Republic of",
    222: "Ukraine",
    223: "Uganda",
    224: "United Kingdom",
    225: "United States Minor Outlying Islands",
    226: "Uruguay",
    227: "Uzbekistan",
    228: "Holy See (Vatican City State)",
    229: "Saint Vincent and the Grenadines",
    230: "Venezuela",
    231: "Virgin Islands, British",
    232: "Virgin Islands, U.S.",
    233: "Viet Nam",
    234: "Vanuatu",
    235: "Wallis and Futuna",
    236: "Samoa",
    237: "Yemen",
    238: "Mayotte",
    239: "South Africa",
    240: "Zambia",
    241: "Zimbabwe",
    242: "Curaçao",
    243: "Sint Maarten",
    244: "Caribbean Netherlands",
    245: "Montenegro",
    246: "Serbia",
    247: "South Sudan",
    248: "Guernsey",
    249: "Isle of Man",
    250: "Kosovo",
}


def resolve_country_id(country_id) -> str:
    """Convert a countryId value to a country name.

    Accepts int, float (e.g. from pandas read_csv), or string representations.
    Returns 'Unknown (ID: X)' for IDs not in the table.
    """
    try:
        if isinstance(country_id, float) and math.isnan(country_id):
            return "Unknown"
        cid = int(float(country_id))
    except (TypeError, ValueError):
        return str(country_id) if country_id is not None else "Unknown"
    return _ID_TO_NAME.get(cid, f"Unknown (ID: {cid})")
